#!/usr/bin/python

"""
- Verifies the derivatives of curves are always negative
- Plots the curves generated by curve_sandwich
"""

import numpy as np
import matplotlib.pyplot as plt
plt.style.use('seaborn-v0_8-colorblind')

from os import makedirs

quiet = False

def notification(info):
  if (quiet == False):
    print(info)

fig_dpi = 300

fig_dir = "plots/curve_sandwich"
data_dir = "data/sims/curve_sandwich"
makedirs(fig_dir, exist_ok = True)

## 0)

notification("Reading `gr.dat`")
gr_integration = np.loadtxt("data/sims/gr/gr.dat", comments='#')

notification("Reading sandwich_curves")
x = np.loadtxt(data_dir+"/x_grid.dat", comments='#')

# Columnas: y // e_j
#           0     j(->4)

m03p01l17 = np.loadtxt(data_dir+"/m03p01l1.0E-17.dat", comments='#')
m03p01l22 = np.loadtxt(data_dir+"/m03p01l1.0E-22.dat", comments='#')
m03p01l27 = np.loadtxt(data_dir+"/m03p01l1.0E-27.dat", comments='#')

m08p02l17 = np.loadtxt(data_dir+"/m08p02l1.0E-17.dat", comments='#')
m08p02l22 = np.loadtxt(data_dir+"/m08p02l1.0E-22.dat", comments='#')
m08p02l27 = np.loadtxt(data_dir+"/m08p02l1.0E-27.dat", comments='#')

m10p10l17 = np.loadtxt(data_dir+"/m10p10l1.0E-17.dat", comments='#')
m10p10l22 = np.loadtxt(data_dir+"/m10p10l1.0E-22.dat", comments='#')
m10p10l27 = np.loadtxt(data_dir+"/m10p10l1.0E-27.dat", comments='#')

sandwich_curves = [m03p01l17, m08p02l17, m10p10l17,
                   m03p01l22, m08p02l22, m10p10l22,
                   m03p01l27, m08p02l27, m10p10l27]

mp_pairs = np.loadtxt(data_dir+"/mp.dat", comments="#", dtype=int)
l = np.loadtxt(data_dir+"/l.dat", comments="#")


## 1)

def slope_check(x, dy):
  change = False
  for j in range(3,len(x)-2):
    sign = dy[j] * dy[j + 1]
    if ( sign < 0.0 ):
      print("Change of slope sign!")
      print("x = {}".format(x(j)))
      change = True
  if (change == False):
    print("No slope sign change")

for i in range(len(sandwich_curves)):
  print("Checking y' slope for {}th data file".format(i+1))
  slope_check(x, sandwich_curves[i][:,1])

## 2)

notification("Creating plots...")

for i in range(0,9,3):

  # Solutions
  plt.figure()

  plt.title("Solutions (l = {})".format(l[i//3]))

  plt.xlabel(r"$ \ln{\frac{a}{a_0}} $")
  plt.ylabel(r"$ \ln{\frac{H}{H_0}} $")

  plt.ylim(-5,75)

  plt.plot(gr_integration[0:380,0], gr_integration[0:380,1], '--', label="GR", color='0.5')

  for k in range(3):
    plt.plot(x , sandwich_curves[i+k][:,0], label="m = {}, p = {}"
             .format(mp_pairs[k,0], mp_pairs[k,1]))

    plt.legend(loc="lower left", frameon=False)

  plt.savefig(fig_dir+"/sol_{}.png".format(i//3), dpi=fig_dpi)
  plt.close()

  # slow-roll 1
  plt.figure()

  plt.title("1st slow-roll parameter (l = {})".format(l[i//3]))

  plt.xlabel(r"$ \ln{\frac{a}{a_0}} $")
  plt.ylabel(r"$ \epsilon_1 $")

  for k in range(3):
    plt.plot(x , sandwich_curves[i+k][:,1], label="m = {}, p = {}"
             .format(mp_pairs[k,0], mp_pairs[k,1]))

    plt.legend(loc="lower left", frameon=False)

  plt.savefig(fig_dir+"/e1_{}.png".format(i//3), dpi=fig_dpi)
  plt.close()

  # slow-roll 2
  plt.figure()

  plt.title("2st slow-roll parameter (l = {})".format(l[i//3]))

  plt.xlabel(r"$ \ln{\frac{a}{a_0}} $")
  plt.ylabel(r"$ \epsilon_2 $")

  for k in range(3):
    plt.plot(x , sandwich_curves[i+k][:,2], label="m = {}, p = {}"
             .format(mp_pairs[k,0], mp_pairs[k,1]))

    plt.legend(loc="lower left", frameon=False)

  plt.savefig(fig_dir+"/e2_{}.png".format(i//3), dpi=fig_dpi)
  plt.close()

  # slow-roll 3
  plt.figure()

  plt.title("3rd slow-roll parameter (l = {})".format(l[i//3]))

  plt.xlabel(r"$ \ln{\frac{a}{a_0}} $")
  plt.ylabel(r"$ \epsilon_3 $")

  plt.ticklabel_format(axis='y', style='scientific')

  for k in range(3):
    plt.plot(x , sandwich_curves[i+k][:,3], label="m = {}, p = {}"
             .format(mp_pairs[k,0], mp_pairs[k,1]))

    plt.legend(loc="lower left", frameon=False)

  plt.savefig(fig_dir+"/e3_{}.png".format(i//3), dpi=fig_dpi)
  plt.close()

  # slow-roll 4
  plt.figure()

  plt.title("4th slow-roll parameter (l = {})".format(l[i//3]))

  plt.xlabel(r"$ \ln{\frac{a}{a_0}} $")
  plt.ylabel(r"$ \epsilon_4 $")

  plt.ticklabel_format(axis='y', style='scientific')

  for k in range(3):
    plt.plot(x , sandwich_curves[i+k][:,4], label="m = {}, p = {}"
             .format(mp_pairs[k,0], mp_pairs[k,1]))

    plt.legend(loc="best", frameon=False)

  plt.savefig(fig_dir+"/e4_{}.png".format(i//3), dpi=fig_dpi)
  plt.close()

exit()
